# Generated by Django 5.2 on 2025-05-01 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_topicdependency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topicdependency',
            options={'verbose_name_plural': 'Topic dependencies'},
        ),
        migrations.AddField(
            model_name='topicdependency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('syllabus', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='topicdependency',
            unique_together={('from_topic', 'to_topic')},
        ),
    ]
