# Generated by Django 5.2 on 2025-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_alter_material_options_alter_syllabus_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['syllabus', 'order'], name='roadmap_top_syllabu_aee026_idx'),
        ),
    ]
